name: tf310
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.10.18  # <-- explicit Python version
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.10.18
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pywin32=311
  - pyzmq=27.1.0
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==6.2.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.13.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - gast==0.4.0
      - google-auth==2.41.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - h5py==3.14.0
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.2
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.7.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.24.3
      - oauthlib==3.3.1
      - opencv-python==4.8.0.76
      - opt-einsum==3.4.0
      - pandas==1.5.3
      - pillow==11.3.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.0.9
      - pytz==2025.2
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.1.3
      - scipy==1.15.3
      - seaborn==0.13.2
      - sympy==1.13.1
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.66.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
